name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    env:
      node-version: 18

    strategy:
      matrix:
        # TODO: re-enable macos
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get install icnsutils graphicsmagick rpm libarchive-tools

    - uses: actions/checkout@v6

    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ env.node-version }}
        cache: npm

    - run: npm ci

    - run: npm run lint

    - run: npm run format:check

    - run: npm run test

    - name: Prepare integration test dependencies
      if: runner.os == 'Linux'
      run: ./scripts/start-test-integration-deps.sh

    - name: Build app for e2e test
      if: runner.os == 'Linux'
      run: npm run compile

    - name: Fix chrome-sandbox permissions
      if: runner.os == 'Linux'
      run: sudo chown root ./node_modules/electron/dist/chrome-sandbox && sudo chmod 4755 ./node_modules/electron/dist/chrome-sandbox

    - name: Run e2e test
      if: runner.os == 'Linux'
      run: xvfb-run --auto-servernum npm run test:e2e

    - run: npm run dist -- --publish never

    - name: Upload artifacts
      uses: actions/upload-artifact@v5
      with:
        name: ${{ matrix.os }}
        path: dist
